//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace iServe.Models {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "communicationType", Namespace = "", IsNullable = false)]
    public partial class CommunicationType {
        private string nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "name")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id", DataType = "integer")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "communication", Namespace = "", IsNullable = false)]
    public partial class Communication {
        private Household householdField;

        private Person personField;

        private CommunicationType communicationTypeField;

        private string communicationValueField;

        private string communicationGeneralType;

        private string searchCommunicationValueField;

        private bool listedField;

        private string communicationCommentField;

        private System.Nullable<System.DateTime> createdDateField;

        private System.Nullable<System.DateTime> lastUpdatedDateField;

        private string uriField;

        private string idField;

        public Communication() {
            this.createdDateField = new System.DateTime(0);
            this.lastUpdatedDateField = new System.DateTime(0);
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "household")]
        public Household Household {
            get {
                return this.householdField;
            }
            set {
                this.householdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "person")]
        public Person Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "communicationType")]
        public CommunicationType CommunicationType {
            get {
                return this.communicationTypeField;
            }
            set {
                this.communicationTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "communicationGeneralType")]
        public string CommunicationGeneralType {
            get {
                return this.communicationGeneralType;
            }
            set {
                this.communicationGeneralType = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "communicationValue")]
        public string CommunicationValue {
            get {
                return this.communicationValueField;
            }
            set {
                this.communicationValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "searchCommunicationValue")]
        public string SearchCommunicationValue {
            get {
                return this.searchCommunicationValueField;
            }
            set {
                this.searchCommunicationValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "listed")]
        public bool Listed {
            get {
                return this.listedField;
            }
            set {
                this.listedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "communicationComment")]
        public string CommunicationComment {
            get {
                return this.communicationCommentField;
            }
            set {
                this.communicationCommentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "createdDate", IsNullable = true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "lastUpdatedDate", IsNullable = true)]
        public System.Nullable<System.DateTime> LastUpdatedDate {
            get {
                return this.lastUpdatedDateField;
            }
            set {
                this.lastUpdatedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}