//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace iServe.Models {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "weblink", Namespace = "", IsNullable = true)]
    public partial class Weblink {

        private string userIDField;

        private string passwordHintField;

        private string passwordAnswerField;

        public Weblink() {
            this.userIDField = "";
            this.passwordHintField = "";
            this.passwordAnswerField = "";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "userID")]
        
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "passwordHint")]
        
        public string PasswordHint {
            get {
                return this.passwordHintField;
            }
            set {
                this.passwordHintField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "passwordAnswer")]
        
        public string PasswordAnswer {
            get {
                return this.passwordAnswerField;
            }
            set {
                this.passwordAnswerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "subStatus", Namespace = "", IsNullable = false)]
    public partial class SubStatus {
        private string nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "name")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "status", Namespace = "", IsNullable = false)]
    public partial class Status {

        private SubStatus subStatusField;

        private string uriField;

        private string nameField;

        private short idField;

        private string dateField;

        private string commentField;

        public Status() {
            this.dateField = "0001-01-01T00:00:00";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "name")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "comment")]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "date")]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "subStatus", IsNullable = false)]
        public SubStatus SubStatus {
            get {
                return this.subStatusField;
            }
            set {
                this.subStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
       
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public short ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "school", Namespace = "", IsNullable = false)]
    public partial class School {
        private string nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "name")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "person", Namespace = "", IsNullable = false)]
    public partial class Person {

        private string titleField;

        private string salutationField;

        private string prefixField;

        private string firstNameField;

        private string lastNameField;

        private string suffixField;

        private string middleNameField;

        private string goesByNameField;

        private string formerNameField;

        private System.Nullable<Gender> genderField;

        private System.Nullable<System.DateTime> dateOfBirthField;

        private System.Nullable<MaritalStatus> maritalStatusField;

        private HouseholdMemberType householdMemberTypeField;

        private string isAuthorizedField;

        private Status statusField;

        private Occupation occupationField;

        private string employerField;

        private School schoolField;

        private Denomination denominationField;

        private string formerChurchField;

        private string barCodeField;

        private string memberEnvelopeCodeField;

        private string defaultTagCommentField;

        private Weblink weblinkField;

        private string solicitField;

        private string thankField;

        private System.Nullable<System.DateTime> firstRecordField;

        private object lastMatchDateField;

        private System.Nullable<System.DateTime> createdDateField;

        private System.Nullable<System.DateTime> lastUpdatedDateField;

        private string uriField;

        private string idField;

        private string oldIDField;

        private string oldHouseholdIDField;

        private string iCodeField;

        private string householdIDField;

        public Person() {
            this.dateOfBirthField = new System.DateTime(0);
            this.firstRecordField = new System.DateTime(0);
            this.createdDateField = new System.DateTime(0);
            this.lastUpdatedDateField = new System.DateTime(0);
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "title", IsNullable = true)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "salutation", IsNullable = true)]
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "prefix", IsNullable = true)]
        public string Prefix {
            get {
                return this.prefixField;
            }
            set {
                this.prefixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "firstName", IsNullable = true)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "lastName")]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "suffix", IsNullable = true)]
        public string Suffix {
            get {
                return this.suffixField;
            }
            set {
                this.suffixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "middleName", IsNullable = true)]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "goesByName", IsNullable = true)]
        public string GoesByName {
            get {
                return this.goesByNameField;
            }
            set {
                this.goesByNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "formerName", IsNullable = true)]
        public string FormerName {
            get {
                return this.formerNameField;
            }
            set {
                this.formerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "gender", IsNullable = true)]
        public System.Nullable<Gender> Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "dateOfBirth", IsNullable = true)]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "maritalStatus", IsNullable = true)]
        public System.Nullable<MaritalStatus> MaritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "householdMemberType")]
        public HouseholdMemberType HouseholdMemberType {
            get {
                return this.householdMemberTypeField;
            }
            set {
                this.householdMemberTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "isAuthorized", IsNullable = true)]
        public string IsAuthorized {
            get {
                return this.isAuthorizedField;
            }
            set {
                this.isAuthorizedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "status", IsNullable = true)]
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "occupation", IsNullable = true)]
        public Occupation Occupation {
            get {
                return this.occupationField;
            }
            set {
                this.occupationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "employer", IsNullable = true)]
        public string Employer {
            get {
                return this.employerField;
            }
            set {
                this.employerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "school", IsNullable = true)]
        public School School {
            get {
                return this.schoolField;
            }
            set {
                this.schoolField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "denomination", IsNullable = true)]
        public Denomination Denomination {
            get {
                return this.denominationField;
            }
            set {
                this.denominationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "formerChurch", IsNullable = true)]
        public string FormerChurch {
            get {
                return this.formerChurchField;
            }
            set {
                this.formerChurchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "barCode", IsNullable = true)]
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "memberEnvelopeCode", IsNullable = true)]
        public string MemberEnvelopeCode {
            get {
                return this.memberEnvelopeCodeField;
            }
            set {
                this.memberEnvelopeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "defaultTagComment", IsNullable = true)]
        public string DefaultTagComment {
            get {
                return this.defaultTagCommentField;
            }
            set {
                this.defaultTagCommentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "weblink", IsNullable = true)]
        public Weblink Weblink {
            get {
                return this.weblinkField;
            }
            set {
                this.weblinkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "solicit", IsNullable = true)]
        public string Solicit {
            get {
                return this.solicitField;
            }
            set {
                this.solicitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "thank", IsNullable = true)]
        public string Thank {
            get {
                return this.thankField;
            }
            set {
                this.thankField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "firstRecord", IsNullable = true)]
        public System.Nullable<System.DateTime> FirstRecord {
            get {
                return this.firstRecordField;
            }
            set {
                this.firstRecordField = value;
            }
        }

        /// <remarks/>
        // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='0001-01-01T00:00:00' attribute.
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "lastMatchDate", IsNullable = true)]
        public object LastMatchDate {
            get {
                return this.lastMatchDateField;
            }
            set {
                this.lastMatchDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "createdDate", IsNullable = true)]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "lastUpdatedDate", IsNullable = true)]
        public System.Nullable<System.DateTime> LastUpdatedDate {
            get {
                return this.lastUpdatedDateField;
            }
            set {
                this.lastUpdatedDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "oldId")]
        public string OldID {
            get {
                return this.oldIDField;
            }
            set {
                this.oldIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "oldHouseholdID")]
        public string OldHouseholdID {
            get {
                return this.oldHouseholdIDField;
            }
            set {
                this.oldHouseholdIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "iCode")]
        public string ICode {
            get {
                return this.iCodeField;
            }
            set {
                this.iCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "householdID", DataType = "integer")]
        public string HouseholdID {
            get {
                return this.householdIDField;
            }
            set {
                this.householdIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "gender", Namespace = "", IsNullable = true)]
    public enum Gender {

        /// <remarks/>
        Male,

        /// <remarks/>
        Female,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "maritalStatus", Namespace = "", IsNullable = true)]
    public enum MaritalStatus {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Child/Yth")]
        ChildYth,

        /// <remarks/>
        Divorced,

        /// <remarks/>
        Married,

        /// <remarks/>
        Separated,

        /// <remarks/>
        Single,

        /// <remarks/>
        Widow,

        /// <remarks/>
        Widower,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "householdMemberType", Namespace = "", IsNullable = false)]
    public partial class HouseholdMemberType {

        private HouseholdMemberTypeName nameField;

        private string uriField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "name", Namespace = "")]
        public HouseholdMemberTypeName Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
 
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id", DataType = "integer")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }        
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum HouseholdMemberTypeName {

        /// <remarks/>
        Head,

        /// <remarks/>
        Spouse,

        /// <remarks/>
        Child,

        /// <remarks/>
        Other,

        /// <remarks/>
        Visitor,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "occupation", Namespace = "", IsNullable = false)]
    public partial class Occupation {
        private string nameField;

        private string uriField;

        private string idField;

        private OccupationDescription descriptionField;

        private bool descriptionFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "name")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "description")]
        public OccupationDescription Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DescriptionSpecified {
            get {
                return this.descriptionFieldSpecified;
            }
            set {
                this.descriptionFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum OccupationDescription {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(ElementName = "denomination", Namespace = "", IsNullable = false)]
    public partial class Denomination {
        private string nameField;

        private string uriField;

        private string idField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName = "name")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "uri", DataType = "anyURI")]
        public string Uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName = "id")]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}